# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_vbf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postt',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='postt',
            options={'verbose_name': 'Postt', 'verbose_name_plural': 'Postts'},
        ),
    ]
